name = "RBMsAnnealedImportanceSampling"
uuid = "f4818a02-fb31-488d-84ee-227add8f92b8"
authors = ["Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"]
version = "2.0.2-DEV"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogStatFunctions = "1b3c2205-da69-4893-b2df-717075b12251"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FillArrays = "0.12, 0.13, 1"
LogStatFunctions = "1"
RestrictedBoltzmannMachines = "1, 2, 3"
Statistics = "1"
julia = "1.8"
